FROM python:3.8

RUN apt-get update \
	&& apt-get install -y --no-install-recomends \
		postgresql-client \
	&& rm rf /var/lib/apt/lists/* \
	&& apt-get install git

RUN git clone https://github.com/TBS093A/trade-app-backend.git
https://github.com/TBS093A/trade-app-backend.git
