# Generated by Django 2.2.6 on 2019-12-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggers',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
