# Generated by Django 2.2.6 on 2019-12-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0002_triggers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggers',
            name='date_of_trigger',
            field=models.CharField(max_length=255),
        ),
    ]
