# Generated by Django 2.2.6 on 2020-01-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalApp', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
